# Generated by Django 3.1.3 on 2021-05-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(),
        ),
    ]
