# Generated by Django 3.1.3 on 2021-05-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0004_businesscontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(max_length=200)),
                ('monday', models.CharField(max_length=200)),
                ('tuesday', models.CharField(max_length=200)),
                ('wednesday', models.CharField(max_length=200)),
                ('thursdayday', models.CharField(max_length=200)),
                ('friday', models.CharField(max_length=200)),
                ('saturday', models.CharField(max_length=200)),
            ],
        ),
    ]
