# Generated by Django 3.1.3 on 2021-05-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0005_businesstime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstime',
            old_name='thursdayday',
            new_name='thursday',
        ),
    ]
