# Generated by Django 3.1.3 on 2021-05-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0006_auto_20210516_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
    ]
