# Generated by Django 3.1.3 on 2021-05-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0007_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
