# Generated by Django 3.1.3 on 2021-05-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0009_cart_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
