# Generated by Django 3.1.3 on 2021-05-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0012_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='count',
        ),
    ]
