# Generated by Django 3.1.3 on 2021-05-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0014_auto_20210522_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='c_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
