# Generated by Django 3.1.3 on 2021-05-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0016_auto_20210522_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
