# Generated by Django 3.1.3 on 2021-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0020_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Packet', 'Packet'), ('Crate', 'Crate'), ('Liter', 'Liter'), ('Crate', 'Crate'), ('Whole', 'Whole'), ('Piece', 'Piece')], max_length=50),
        ),
    ]
