# Generated by Django 3.1.3 on 2021-05-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0021_auto_20210523_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
    ]
