# Generated by Django 3.1.3 on 2021-05-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0022_auto_20210523_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(),
        ),
    ]
