# Generated by Django 3.1.3 on 2021-05-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0024_notice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=9856456545, max_length=10),
            preserve_default=False,
        ),
    ]
