# Generated by Django 3.1.3 on 2021-05-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0025_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
