# Generated by Django 3.1.3 on 2021-05-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0027_remove_notice_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('about_image', models.ImageField(upload_to='about_image')),
            ],
        ),
    ]
