# Generated by Django 3.1.3 on 2021-05-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0028_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
