# Generated by Django 3.1.3 on 2021-05-27 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0030_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
