# Generated by Django 3.1.3 on 2021-05-27 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0031_location_location_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='location',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='location'),
            preserve_default=False,
        ),
    ]
