# Generated by Django 3.1.3 on 2021-05-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0033_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField()),
                ('about_image', models.ImageField(upload_to='about_image')),
            ],
        ),
    ]
