# Generated by Django 3.1.3 on 2021-05-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0034_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
