# Generated by Django 3.1.3 on 2021-05-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0035_cartproduct_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
