# Generated by Django 3.1.3 on 2021-05-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0036_auto_20210529_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='kg_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
