# Generated by Django 3.1.3 on 2021-05-30 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0038_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='location_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='twitter',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='youtube',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
