# Generated by Django 3.1.3 on 2021-06-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0042_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Payment with account number', 'Payment with account number')], default='Cash On Delivery', max_length=50),
        ),
    ]
