# Generated by Django 3.1.3 on 2021-06-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0043_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontact',
            name='location',
            field=models.TextField(),
        ),
    ]
