# Generated by Django 3.1.3 on 2021-06-03 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0044_auto_20210603_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscontact',
            name='location_address',
        ),
    ]
