# Generated by Django 3.1.3 on 2021-06-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0046_auto_20210603_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='account_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
