# Generated by Django 3.1.3 on 2021-06-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0047_businesscontact_account_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelpVideo',
            new_name='Help',
        ),
    ]
