# Generated by Django 3.1.3 on 2021-06-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0048_auto_20210603_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('video_link', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='businesscontact',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
