# Generated by Django 3.1.3 on 2021-06-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0049_auto_20210605_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
