# Generated by Django 3.1.3 on 2021-06-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0050_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
