# Generated by Django 3.1.3 on 2021-06-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0051_career_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscontact',
            old_name='google',
            new_name='instagram',
        ),
    ]
