# Generated by Django 3.1.3 on 2021-06-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0054_save_savedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproduct',
            name='kg_quantity',
        ),
    ]
