# Generated by Django 3.1.3 on 2021-06-07 01:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0056_auto_20210607_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproduct',
            name='saved',
        ),
        migrations.AddField(
            model_name='savedproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedproduct',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fresh.customer'),
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
